# Generated by Django 2.2 on 2021-04-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('mp1', models.CharField(max_length=120)),
                ('mp2', models.CharField(max_length=120)),
                ('mp3', models.CharField(max_length=120)),
                ('p1', models.TextField()),
                ('p2', models.TextField()),
                ('p3', models.TextField()),
                ('i1', models.CharField(max_length=120)),
                ('i2', models.CharField(max_length=120)),
                ('i3', models.CharField(max_length=120)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
