# Generated by Django 3.2 on 2021-05-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210427_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('author', models.CharField(max_length=120, null=True)),
                ('tldr', models.TextField(null=True)),
                ('intro', models.TextField(null=True)),
                ('mp1_header', models.CharField(max_length=120, null=True)),
                ('p1', models.TextField(null=True)),
                ('mp2_header', models.CharField(max_length=120, null=True)),
                ('p2', models.TextField(null=True)),
                ('mp3_header', models.CharField(max_length=120, null=True)),
                ('p3', models.TextField(null=True)),
                ('outro', models.TextField(null=True)),
                ('tags', models.CharField(max_length=120, null=True)),
                ('likes', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=120, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
