# Generated by Django 3.2 on 2021-06-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210516_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='mp1_header',
            new_name='p1_heading',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='mp2_header',
            new_name='p2_heading',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='mp3_header',
            new_name='p3_heading',
        ),
    ]
