# Generated by Django 3.2 on 2021-07-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_testarticle_testauthor_testtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testarticle',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
